export const SET_INSTANCE_ID = 'SET_INSTANCE_ID';
export const CREATE_INSTANCE = 'CREATE_INSTANCE';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_DELIVERY_OPTIONS = 'GET_DELIVERY_OPTIONS';

export const READ_UPDATE_PROCESS = 'READ_UPDATE_PROCESS';
export const SELECT_PRODUCTS = 'SELECT_PRODUCTS';

export const CREATE_ORDER = 'CREATE_ORDER';
export const UPDATE_CUSTOMER_INFO = 'UPDATE_CUSTOMER_INFO';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';

export const SET_PREFERENCES = 'SET_PREFERENCES';
